services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"  # Porta para o acesso do n8n local (não exposta para o público)
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - DB_SQLITE_DATABASE=/data/database.sqlite  # Armazenamento do banco de dados SQLite
      - VUE_APP_URL_BASE_API=https://n8n.seudominio.com  # Substitua com o domínio configurado
    volumes:
      - ./n8n-data:/data  # Persistência de dados
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
