services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"  # Porta para o acesso do n8n local (não exposta para o público)
    environment:
      - N8N_HOST=n8n.gmxindustrial.com.br
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.gmxindustrial.com.br
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - /home/src/.n8n:/home/node/.n8n
volumes:
  n8n_data:
    external: true
